#!/usr/bin/python

from PySide import QtGui
from graide import main
from argparse import ArgumentParser
import sys

app = QtGui.QApplication(sys.argv)
p = ArgumentParser()
p.add_argument("font", help="Font .ttf file to process")
p.add_argument("-a","--ap",help="AP XML database file for font")
p.add_argument("-g","--gdx",help="grcompiler debug output file")
p.add_argument("-r","--results",help="graphite JSON debug output")
p.add_argument("-s","--size",default=40,type=int,help="Size of glyphs to render in pixels")
args = p.parse_args()

if args.font :
    mainWindow = main.MainWindow(args.font, args.ap, args.results, args.size, args.gdx)
    mainWindow.show()
    sys.exit(app.exec_())
