.TH GRAIDE 1
.SH NAME
graide \- GRAphite Integrated Development Environment
.SH SYNOPSIS
.B graide
[\-h] [\-p PROJECT] [\-f FONT] [\-a AP] [\-g GDX] [\-r RESULTS] [\-s SIZE]
.SH DESCRIPTION
Graide is an integrated development environment that can be used to develop fonts with Graphite features.
Graphite is a "smart font" system developed specifically to handle the complexities of lesser-known languages of the world.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-p\fR, \fB\-\-project\fR PROJECT
Project configuration file
.TP
\fB\-f\fR, \fB\-\-font\fR FONT
Font .ttf file to process
.TP
\fB\-a\fR, \fB\-\-ap\fR AP
AP XML database file for font
.TP
\fB\-g\fR, \fB\-\-gdx\fR GDX
grcompiler debug output file
.TP
\fB\-r\fR, \fB\-\-results\fR RESULTS
graphite JSON debug output
.TP
\fB\-s\fR, \fB\-\-size\fR SIZE
Size of glyphs to render in pixels
